# Generated by Django 5.2.6 on 2025-09-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
